# SPDX-FileCopyrightText: 2023 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: CC-BY-SA-3.0

# pdsite configuration

theme: default
inputextension: .md
outputfolder: build/html

# Site-wide template variables

sitename: "Git Internals"
site-url: "https://hoijui.github.io"
site-base-path: /git-internals-doc
pagetitle-suffix: ""
footer: ""

