# SPDX-FileCopyrightText: 2024 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

version = 1
SPDX-PackageName = "git-internals-pdf"
SPDX-PackageSupplier = "Robin Vobruba <hoijui.quaero@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/osegermany/git-internals-pdf/"

[[annotations]]
path = ["artwork/title.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2008 Geoffrey Grosenbach <boss@topfunky.com>", "2008 Scott Chacon <schacon@gmail.com>", "2023 Robin Vobruba <hoijui.quaero@gmail.com>"]
SPDX-License-Identifier = "CC-BY-SA-3.0"

[[annotations]]
path = ["artwork/diagrams/**.eps"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2008 Geoffrey Grosenbach <boss@topfunky.com>", "2008 Scott Chacon <schacon@gmail.com>"]
SPDX-License-Identifier = "CC-BY-SA-3.0"

[[annotations]]
path = ["artwork/diagrams/**.png", "artwork/diagrams/**.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2008 Geoffrey Grosenbach <boss@topfunky.com>", "2008 Scott Chacon <schacon@gmail.com>", "2023 Robin Vobruba <hoijui.quaero@gmail.com>"]
SPDX-License-Identifier = "CC-BY-SA-3.0"

[[annotations]]
path = ["artwork/screenshots/**.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2008 Geoffrey Grosenbach <boss@topfunky.com>", "2008 Scott Chacon <schacon@gmail.com>"]
SPDX-License-Identifier = "CC-BY-SA-3.0"

[[annotations]]
path = "code/**.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2008 Scott Chacon <schacon@gmail.com>"]
SPDX-License-Identifier = "CC-BY-SA-3.0"

[[annotations]]
path = "movies/**.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "2008 Scott Chacon <schacon@gmail.com>"
SPDX-License-Identifier = "CC-BY-SA-3.0"
